### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Logan-kwan**
docs(global): Added "The Problem" and "The Solution" to README.MD

README.MD now has headers The Problem and The Solution with relevant information from the YouTube video "React Email Final Demo | Google Summer of Code 2022 | GSoC'22 | SCoRe Lab - Leopards Lab"

### CODE REVIEW

**Comment by Logan-kwan** [comment]
also, a small reminder; could you add the hacktoberfest label to the issue? thanks!

**Comment by Logan-kwan** [comment]
hi @niloysikdar , i'm probably just going to make a new PR with the conventional commit statements and such. would that be okay with you?

**Comment by niloysikdar** [comment]
Yeah sure. To make things clear for you, you can follow these steps.

Set an environment variable named `NPM_TOKEN` with any random value using 
```bash
set NPM_TOKEN=abcd
```
Then install the dependencies using
```bash
yarn
```
Do the modifications in the README, and run
```bash
git add .
yarn cm
```

Choose the scope and fill the other info from the menu.

**Review by niloysikdar — COMMENTED** [review]
Closing this PR, raise a new Pull Request with the changes.

**Pull request closed without merging**
