### PR TITLE
docs(global): Added "The Problem" and "The Solution" to README.MD

### PR DESCRIPTION
**Pull request by Logan-kwan**
README.MD now has headers The Problem and The Solution with relevant information from the YouTube video "React Email Final Demo | Google Summer of Code 2022 | GSoC'22 | SCoRe Lab - Leopards Lab"

### CODE REVIEW

**Comment by Logan-kwan** [comment]
just a small nitpicky thing; could you add the hacktoberfest tag to the issue? thanks!

**Comment by niloysikdar** [comment]
I've already added the `hacktoberfest` label to the issue. We'll also add the `hacktoberfest` topic to the repo to include your pull request to hacktoberfest.

**Review by niloysikdar — CHANGES_REQUESTED** [review]
Hi @Logan-kwan, as suggested in issue #115, I think it will be best to put it at the very start of the README after the name and description of the package (before the installation process).

**Comment by Logan-kwan** [comment]
alright, thank for the clarification. ill make a new pr and make sure to put the problem and solution at the start of the README

**Pull request closed without merging**
